package:
  name: k8s-sidecar
  version: 1.21.0
  epoch: 0
  description: Sidecar for k8s
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - busybox
      - python3
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/kiwigrid/k8s-sidecar/archive/refs/tags/1.21.0.tar.gz
      expected-sha256: 1a0fa1d01b69ce2e8771b6f3b7405ba03eabe65c559b6ccffc922f448e07908e
  - runs: |
      cd src/
      python -m venv .venv
      .venv/bin/pip install --no-cache-dir -r requirements.txt
      find .venv \( -type d -a -name test -o -name tests \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' \+
      mkdir -p ${{targets.destdir}}/usr/share/k8s-sidecar
      cp -r . ${{targets.destdir}}/usr/share/k8s-sidecar
